{
 "title": "Karpenter Per Node - Export",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "CLUSTER",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_node_labels,cluster)"
    }
   },
   {
    "name": "NODEGROUP",
    "label": "Node Group",
    "query": {
     "query": "label_values(kube_node_labels{cluster=\"$CLUSTER\"},label_nodegroup)"
    }
   },
   {
    "name": "NODEPOOL",
    "label": "NodePool",
    "query": {
     "query": "label_values(kube_node_labels{cluster=\"$CLUSTER\",label_nodegroup=\"$NODEGROUP\"},label_karpenter_sh_nodepool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Interruptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_nodeclaims_terminated{reason=\"interruption\",cluster=\"$CLUSTER\", nodepool=~\"$NODEPOOL\"}) by (nodepool)",
     "legendFormat": "{{nodepool}}"
    }
   ]
  },
  {
   "title": "LifeCycles",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_labels{cluster=\"$CLUSTER\",label_nodegroup=\"$NODEGROUP\", label_karpenter_sh_capacity_type!=\"\"}) by (label_karpenter_sh_capacity_type)",
     "legendFormat": "{{label_karpenter_sh_capacity_type}}"
    }
   ]
  },
  {
   "title": "AZ ",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_labels{cluster=\"$CLUSTER\",label_nodegroup=\"$NODEGROUP\", label_topology_kubernetes_io_zone!=\"\"}) by (label_topology_kubernetes_io_zone)",
     "legendFormat": "{{label_topology_kubernetes_io_zone}}"
    }
   ]
  },
  {
   "title": "Memory / CPU Ratio",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_nodepool_usage{cluster=\"$CLUSTER\",nodepool=~\"$NODEPOOL\",resource_type=\"memory\"} / 1024 /1024 / 1024) / \nsum(karpenter_nodepool_usage{cluster=\"$CLUSTER\",nodepool=~\"$NODEPOOL\",resource_type=\"cpu\"}) "
    }
   ]
  },
  {
   "title": "Total cores $NODEGROUP",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_nodepool_usage{cluster=\"$CLUSTER\",nodepool=~\"$NODEPOOL\",resource_type=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Total Memory (Gb)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_nodepool_usage{cluster=\"$CLUSTER\",nodepool=~\"$NODEPOOL\",resource_type=\"memory\"} /1024 /1024 /1024)"
    }
   ]
  },
  {
   "title": "NodeGroup Usage Out Of limit",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_nodepool_usage{cluster=\"$CLUSTER\", nodepool=~\"$NODEPOOL\"}) by (resource_type, nodepool) / sum(karpenter_nodepool_limit{cluster=\"$CLUSTER\", nodepool=~\"$NODEPOOL\"}) by (resource_type, nodepool)",
     "legendFormat": "{{resource_type}} {{nodepool}}"
    }
   ]
  },
  {
   "title": "Instance Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_labels{cluster=\"$CLUSTER\",label_nodegroup=\"$NODEGROUP\", label_karpenter_sh_capacity_type!=\"\"}) by (label_node_kubernetes_io_instance_type)",
     "legendFormat": "{{label_node_kubernetes_io_instance_type}}"
    }
   ]
  },
  {
   "title": "Total Created Nodes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_nodes_created{cluster=\"$CLUSTER\", nodepool=~\"$NODEPOOL\"}) by (nodepool)",
     "legendFormat": "Created by {{provisioner}}"
    }
   ]
  },
  {
   "title": "Drift types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_nodeclaims_drifted{cluster=\"$CLUSTER\", nodepool=~\"$NODEPOOL\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Total Removed Nodes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_nodeclaims_terminated{cluster=\"$CLUSTER\", nodepool=~\"$NODEPOOL\"}) by (nodepool, reason)",
     "legendFormat": "Removed by {{provisioner}} {{reason}}"
    }
   ]
  },
  {
   "title": "Spot Costs on $NODEGROUP",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(sum(count(label_replace(kube_node_labels_mixin{cluster=\"$CLUSTER\",label_nodegroup=\"$NODEGROUP\",label_karpenter_sh_capacity_type=\"spot\"}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.+)\")) by (instance_type) * on (instance_type) max(karpenter_cloudprovider_instance_type_price_estimate{cluster=\"$CLUSTER\",capacity_type=\"spot\"}) by (instance_type))[1d])",
     "legendFormat": "Day"
    },
    {
     "expr": "sum_over_time(sum(count(label_replace(kube_node_labels_mixin{cluster=\"$CLUSTER\",label_nodegroup=\"$NODEGROUP\",label_karpenter_sh_capacity_type=\"spot\"}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.+)\")) by (instance_type) * on (instance_type) max(karpenter_cloudprovider_instance_type_price_estimate{cluster=\"$CLUSTER\",capacity_type=\"spot\"}) by (instance_type))[7d])",
     "legendFormat": "Week"
    },
    {
     "expr": "sum_over_time(sum(count(label_replace(kube_node_labels_mixin{cluster=\"$CLUSTER\",label_nodegroup=\"$NODEGROUP\",label_karpenter_sh_capacity_type=\"spot\"}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.+)\")) by (instance_type) * on (instance_type) max(karpenter_cloudprovider_instance_type_price_estimate{cluster=\"$CLUSTER\",capacity_type=\"spot\"}) by (instance_type))[30d])",
     "legendFormat": "Month"
    }
   ]
  },
  {
   "title": "On-Demand Costs on $NODEGROUP",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(sum(count(label_replace(kube_node_labels_mixin{cluster=\"$CLUSTER\",label_nodegroup=\"$NODEGROUP\",label_karpenter_sh_capacity_type=\"on-demand\"}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.+)\")) by (instance_type) * on (instance_type) max(karpenter_cloudprovider_instance_type_price_estimate{cluster=\"$CLUSTER\",capacity_type=\"on-demand\"}) by (instance_type))[1d])",
     "legendFormat": "Day"
    },
    {
     "expr": "sum_over_time(sum(count(label_replace(kube_node_labels_mixin{cluster=\"$CLUSTER\",label_nodegroup=\"$NODEGROUP\",label_karpenter_sh_capacity_type=\"on-demand\"}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.+)\")) by (instance_type) * on (instance_type) max(karpenter_cloudprovider_instance_type_price_estimate{cluster=\"$CLUSTER\",capacity_type=\"on-demand\"}) by (instance_type))[7d])",
     "legendFormat": "Week"
    },
    {
     "expr": "sum_over_time(sum(count(label_replace(kube_node_labels_mixin{cluster=\"$CLUSTER\",label_nodegroup=\"$NODEGROUP\",label_karpenter_sh_capacity_type=\"on-demand\"}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.+)\")) by (instance_type) * on (instance_type) max(karpenter_cloudprovider_instance_type_price_estimate{cluster=\"$CLUSTER\",capacity_type=\"on-demand\"}) by (instance_type))[30d])",
     "legendFormat": "Month"
    }
   ]
  },
  {
   "title": "Spot Hourly Pricing for $NODEGROUP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "count(label_replace(kube_node_labels_mixin{cluster=\"$CLUSTER\",label_nodegroup=\"$NODEGROUP\",label_karpenter_sh_capacity_type=\"spot\"}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.+)\")) by (instance_type) * on (instance_type) max(karpenter_cloudprovider_instance_type_price_estimate{cluster=\"$CLUSTER\",capacity_type=\"spot\"}) by (instance_type)",
     "legendFormat": "{{instance_type}} / Hour"
    },
    {
     "expr": "sum(count(label_replace(kube_node_labels_mixin{cluster=\"$CLUSTER\",label_nodegroup=\"$NODEGROUP\",label_karpenter_sh_capacity_type=\"spot\"}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.+)\")) by (instance_type) * on (instance_type) max(karpenter_cloudprovider_instance_type_price_estimate{cluster=\"$CLUSTER\",capacity_type=\"spot\"}) by (instance_type))",
     "legendFormat": "Total Hourly Price"
    }
   ]
  },
  {
   "title": "On-Demand Hourly Pricing for $NODEGROUP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "count(label_replace(kube_node_labels_mixin{cluster=\"$CLUSTER\",label_nodegroup=\"$NODEGROUP\",label_karpenter_sh_capacity_type=\"on-demand\"}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.+)\")) by (instance_type) * on (instance_type) max(karpenter_cloudprovider_instance_type_price_estimate{cluster=\"$CLUSTER\",capacity_type=\"on-demand\"}) by (instance_type)",
     "legendFormat": "{{instance_type}} Hourly Price"
    },
    {
     "expr": "sum(count(label_replace(kube_node_labels_mixin{cluster=\"$CLUSTER\",label_nodegroup=\"$NODEGROUP\",label_karpenter_sh_capacity_type=\"on-demand\"}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.+)\")) by (instance_type) * on (instance_type) max(karpenter_cloudprovider_instance_type_price_estimate{cluster=\"$CLUSTER\",capacity_type=\"on-demand\"}) by (instance_type))",
     "legendFormat": "Total Hourly Price"
    }
   ]
  },
  { "title": "NodeGroup Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Created/Removed Nodes $NODEGROUP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(karpenter_nodeclaims_created{cluster=\"$CLUSTER\", nodepool=~\"$NODEPOOL\" }[1m])) by (reason)",
     "legendFormat": "[ADD] {{reason}}"
    },
    {
     "expr": "- sum(increase(karpenter_nodeclaims_terminated{cluster=\"$CLUSTER\", nodepool=~\"$NODEPOOL\"}[1m])) by (reason)",
     "legendFormat": "[REM] {{reason}}"
    }
   ]
  },
  {
   "title": "Karpenter Spot Interruptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(karpenter_nodeclaims_terminated{reason=\"interruption\", cluster=\"$CLUSTER\", nodepool=~\"$NODEPOOL\"}[1m])) by (nodepool)",
     "legendFormat": "{{provisioner}}"
    },
    {
     "expr": "sum(karpenter_nodeclaims_terminated{reason=\"interruption\", cluster=\"$CLUSTER\", nodepool=~\"$NODEPOOL\"})",
     "legendFormat": "Total Counter"
    }
   ]
  },
  {
   "title": "Drift Tracker",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(increase(karpenter_nodeclaims_drifted{cluster=\"$CLUSTER\", nodepool=~\"$NODEPOOL\"})) by (type) > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Current Provisioned Cores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum(karpenter_nodepool_usage{resource_type=\"cpu\", cluster=\"$CLUSTER\", nodepool=~\"$NODEPOOL\"}) by (nodepool)",
     "legendFormat": "{{nodepool}}"
    }
   ]
  },
  {
   "title": "Current Provisioned Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(karpenter_nodepool_usage{resource_type=\"memory\", cluster=\"$CLUSTER\", nodepool=~\"$NODEPOOL\"}) by (nodepool)",
     "legendFormat": "{{cluster}} {{nodepool}}"
    }
   ]
  },
  {
   "title": "LifeCycle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "count(kube_node_labels{cluster=\"$CLUSTER\",label_nodegroup=\"$NODEGROUP\", label_karpenter_sh_capacity_type!=\"\"}) by (label_karpenter_sh_capacity_type, label_karpenter_sh_nodepool)",
     "legendFormat": "[{{label_karpenter_sh_capacity_type}}]{{label_karpenter_sh_nodepool }}"
    }
   ]
  },
  {
   "title": "NodeGroup Usage Out Of limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(karpenter_nodepool_usage{cluster=\"$CLUSTER\", nodepool=~\"$NODEPOOL\"}) by (resource_type) / sum(karpenter_nodepool_limit{cluster=\"$CLUSTER\", nodepool=~\"$NODEPOOL\"}) by (resource_type)",
     "legendFormat": "{{resource_type}}"
    }
   ]
  },
  {
   "title": "Instance Types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "count(kube_node_labels{cluster=\"$CLUSTER\",label_nodegroup=\"$NODEGROUP\", label_karpenter_sh_capacity_type!=\"\"}) by (label_node_kubernetes_io_instance_type)",
     "legendFormat": "{{label_node_kubernetes_io_instance_type}}"
    }
   ]
  },
  {
   "title": "Instance Types, lifecycle and zone",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "count(kube_node_labels{cluster=\"$CLUSTER\",label_nodegroup=\"$NODEGROUP\", label_karpenter_sh_capacity_type!=\"\"}) by (label_node_kubernetes_io_instance_type,label_karpenter_sh_capacity_type, label_topology_kubernetes_io_zone)",
     "legendFormat": "[{{label_topology_kubernetes_io_zone}}][{{label_karpenter_sh_capacity_type}}]{{label_node_kubernetes_io_instance_type}}"
    }
   ]
  }
 ]
}